services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - FRONTEND_DEBUGGING_PORT=${FRONTEND_DEBUGGING_PORT}
    container_name: ${FRONTEND_CONTAINER_NAME}
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_DEBUGGING_PORT=${FRONTEND_DEBUGGING_PORT}
      - PYTHONUNBUFFERED=1
      - DEBUG=True # Optional: Set an environment variable to indicate debugging mode
    command: >
      bash -c "pip install debugpy && 
               python -m debugpy --wait-for-client --listen 0.0.0.0:${FRONTEND_DEBUGGING_PORT} -m streamlit run frontend_app/0_👋_Introduction.py --server.port=${FRONTEND_PORT} --server.address=0.0.0.0 --server.runOnSave=True"
    volumes:
      - ./src/frontend:/frontend
    ports:
      - "${FRONTEND_DEBUGGING_PORT}:${FRONTEND_DEBUGGING_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_DEBUGGING_PORT=${BACKEND_DEBUGGING_PORT}
    container_name: ${BACKEND_CONTAINER_NAME}
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_DEBUGGING_PORT=${BACKEND_DEBUGGING_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}    
      - PYTHONUNBUFFERED=1
      - DEBUG=True 
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:${BACKEND_DEBUGGING_PORT} -m uvicorn app.main:app  --host 0.0.0.0 --port ${BACKEND_PORT} --reload"]
    ports:
      - "${BACKEND_DEBUGGING_PORT}:${BACKEND_DEBUGGING_PORT}"
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./src/backend:/backend
    depends_on:
      - db

  db:
    image: mysql:9.0.0
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql:/var/lib/mysql
